### ISSUE TITLE
bsdtar and undeclared dependency

### ISSUE THREAD

**Issue by voidpin** [tsujan/Arqiver#12]
@tsujan I've packaged `featherpad`, `feathernotes` and `arqiver` for NetBSD. These are now on the main pkgsrc-branch and available to all pkgsrc-users.
There're a few issues with `arqiver` that I feel I should make you aware of. First of all there is an undeclared dependency, the package needs `xdg-utils` for `xdg-open`. At first I didn't notice this as I had `xdg-utils` installed but, the person reviewing the package found it when building in a sandbox environment. Could this be added to the dependency list?

Then, on `backends.cpp`
There's the assumption that `tar` on non-Linux systems equals `bsdtar`. This is only true for FreeBSD and Minix, not for OpenBSD or NetBSD.
A suggestion would be to replace both `tar` and `bsdtar` definitions with the more general `${TOOLS_PATH.bsdtar}`, otherwise a rather complex `ifdef` sequence would be necessary.
As we are at it, it would be also good to replace the invocation of `gzip` and `7z` with `${TOOLS_PATH.gzip}` and `${TOOLS_PATH.7za}`, respectively.

Last, replacing `xdg-open` with `${PREFIX}/bin/xdg-open` would make it all more portable.

These are just suggestions.
Regards

**Comment by tsujan** [comment]
First, thanks for your comment!

> First of all there is an undeclared dependency, the package needs xdg-utils for xdg-open

This kind of thing is sometimes called "packaging dependency"; the program doesn't need it to be compiled. It's a downstream job.

> There's the assumption that tar on non-Linux systems equals bsdtar. This is only true for FreeBSD and Minix, not for OpenBSD or NetBSD.

Then, `ifdef` should be used. I'll search the Internet for OpenBSD or NetBSD...

> Last, replacing xdg-open with ${PREFIX}/bin/xdg-open would make it all more portable.

`${PREFIX}` or `TOOLS_PATH` doesn't have meaning on Linux. We have the environment variable `PATH` and `xdg-open` -- or any other executable -- should be inside it, so that it could be called in command-line as `xdg-open`; otherwise, it'll be useless.

I don't know about `NetBSD` but if, for example, you can't use `xdg-open https://github.com/` inside a terminal with it, you practically don't have `xdg-open` -- which would be very strange to me (it reminds me of MS Windows). Another example: if you install `featherpad`, you should be able to run it with only `featherpad` in a terminal.

**Comment by dhgutteridge** [comment]
If you explicitly want bsdtar from libarchive (which seems to be the case, given that's what you expect on Linux, and the requirement you state), the situation is complicated, depending on the BSD in question. All formal NetBSD releases until 9.0 (out last week) use the historical BSD pax as tar, not bsdtar from libarchive. The same is true for all OpenBSD releases, from what I see (going by the OpenBSD man page: [https://man.openbsd.org/tar](https://man.openbsd.org/tar)) -- I don't use OpenBSD.

For NetBSD, I doubt you want to go into that much trouble of special-casing these things (i.e., bringing in OS-specific headers that define the release you're compiling under). In NetBSD's packaging, we presently specify Arqiver must use bsdtar, and then leave it to our build infrastructure to decide whether bsdtar needs to be built as an extra dependency, or whether it's already available in the base installed system. (This now needs tweaks as of 9.0, but that's our problem to deal with.)

**Comment by tsujan** [comment]
Thanks for the detailed info!

Although my focus is on Linux (the only system I have), it'll be good if Arqiver could work on all *BSD flavors too. So, according to your info, I should change it to `bsdtar` for NetBSD and, perhaps, OpenBSD. I'll do so as soon as I find some time to do a search on the Internet.

Arqiver technically doesn't *depend* on `bsdtar` or `libarchive`; it's a Qt skin that *runs* `bsdtar` appropriately. `bsdtar` belongs to `libarchive` on Linux. Whether `tar` has the same features and command-line options or not, I don't know yet (it didn't years ago) but I should investigate it at some point. What I know is that `bsdtar` (`libarchive`) is very feature-rich; hence, calling it in Arqiver, alongside `7z` and `gzip`. The goal has been the creation of a light, reliable and flexible Qt skin that can handle common archive formats efficiently.

**Comment by dhgutteridge** [comment]
To clarify, on, say, NetBSD 8.1, it would be "bsdtar" (installed as /usr/pkg/bin/bsdtar by default), whereas on NetBSD 9.0, it would be "tar" (installed as /bin/tar, symlinked as /usr/bin/tar). The distinction being, the first is treated as third-party package, the second is a core component (since it replaced BSD pax as tar in the base distribution). So the naming itself is the challenge/complexity.

**Comment by tsujan** [comment]
LOL! In that case, yes, it's too complex.

Maybe, I need to add an option for it in Preferences and solve the problem once for all by asking the (*BSD) user. The option could be there only with *BSD. I think that's the best approach.

I reopen this until it's done.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Arqiver/commit/868bd4b082c73ffc95a68c6b17fb674760d13983

In non-Linux systems, Preferences dialog has an extra option:

![binary_option](https://user-images.githubusercontent.com/981076/75106212-260c1880-562f-11ea-8b4f-faff39ee429b.png)

**Comment by voidpin** [comment]
@tsujan Awesome!
Thanks for your support.

**Comment by tsujan** [comment]
@voidpin Thanks for your report!
