### ISSUE TITLE
Is there any chance of supporting rar archives, at least for extraction?

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/Arqiver#19]
I've managed to package 0.6.0 for Debian-based MX Linux repos, but that seems to be the only somewhat common format it can't handle. https://repology.org/project/arqiver/versions

Offtopic--wonder why Debian's not tracking featherpad updates upstream any longer, too.

**Comment by tsujan** [comment]
Arqiver supports formats that are supported by `libarchive`, `7z` and `gzip`. I'll see if one of them cant extract `rar`. Will tell you later.

> why Debian's not tracking featherpad updates upstream any longer, too.

The Debian maintainer of some packages suddenly disappeared several months ago. Since then, Debian doesn't have an up-to-date LXQt, FeatherPad, FeatherNotes,... Debian can be bureaucratic; it might not get another maintainer for a long time.

**Comment by tsujan** [comment]
Update:
I succeeded in opening a sample rar file with Arqiver by pressing "Open Archive" (`Ctrl+O`) and then selecting "Show All Files" in the file dialog. Arqiver could also extract it. Could you confirm that too?

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Arqiver/commit/f1ad8deee3deb182fa699501dfa28202d6a6fdfe

`7z` had a good read-only support for RAR archives and I used it instead of `bsdtar`. Will release 0.6.1 if no important change comes to my mind for a while.

Thanks for the suggestion!

**Comment by stevenpusser** [comment]
Thanks for the fix! That will make it a great replacement for the heavy
Ark, which I still use in XFCE.

I'm still keeping Featherpad, Kvantum, and Notes current for MX, but I'm
also having limited time to do it due to the pandemic. We are recruiting
and training some more packagers for MX, thankfully. I'm looking at
packaging that icon theme theme you have (the name escapes me), too.

**Comment by tsujan** [comment]
> it a great replacement for the heavy Ark, which I still use in XFCE.

I couldn't tolerate Ark in KDE either.

> I'm still keeping Featherpad, Kvantum, and Notes current for MX

That's good news. Thanks!

I hope some dev will do something for Debian too.

> ... the name escapes me.

Its name is Plataro. It's for Qt-based DEs like LXQt and KDE. I don't add icons for GTK DEs to it because Gnome has added the string "gnome" to some mime icons and doesn't want to correct that mistake. Moreover, GTK doesn't render SVG icons well.
