### ISSUE TITLE
"Extract to…"

### ISSUE THREAD

**Issue by butyoutried** [tsujan/Arqiver#75]
When I select "Extract to..." from PCManFM-Qt context menu, latest Arqiver shows file dialog AND the main window, which is completely unnecessary at this moment. Moreover, the "Cancel" button closes only file dialog, but not Arqiver's main window.

Tried several other archivers (Xarchiver, Ark, LXQt Archiver), on "Extract to..." each of them shows the file dialog only. Could you please implement such behaviour?

**Comment by tsujan** [comment]
The main window shows that the extraction is in progress (Arqiver doesn't have a separate progress dialog by design). Moreover, if the operation is cancelled, the main window should remain open and loaded, because the user might want to do another operation with it.

> .... which is completely unnecessary... Tried several other archivers ...

If I was happy with other archivers, I wouldn't make Arqiver ;) Tastes differ.

**Comment by butyoutried** [comment]
Yes, but at the same time "Compress" shows file dialog only, and main window with built-in progress indicator appears and then closes automatically after it.

Thanks anyway :)

**Comment by tsujan** [comment]
> Yes, but at the same time "Compress" shows file dialog only

The main window is shown with "Compress" too because, with heavy files/folders, the user may want to cancel the operation.
