### ISSUE TITLE
 i not found appimage format file

### ISSUE THREAD

**Issue by newyorkthink** [tsujan/Arqiver#97]
![image](https://github.com/tsujan/Arqiver/assets/87791643/f2df3323-e1e1-4379-b55d-e4703c260e16)

you have not support appimage

**Comment by tsujan** [comment]
> you have not support appimage

Please don't open a report about a closed one; you could add your comments to closed reports too.

As I said at https://github.com/tsujan/Arqiver/issues/96#issuecomment-1633801933, The support was added in 2021; see https://github.com/tsujan/Arqiver/releases/tag/V0.9.0. You could have tried to open an AppImage file, instead of opening this page.

**Comment by redtide** [comment]
I guess they meant that you don't provide an AppImage release package?
If you think to do it I might propose a PR with a GitHub Actions that builds/tests code and creates both AppImage and source code archive when tagging releases. It might be copied and make it work for other projects as well with minimal editing.

**Comment by tsujan** [comment]
> I guess they meant that you don't provide an AppImage release package?

I don't and won't provide any binary.
